version: '3'

services:
  blue:
    image: nginx:latest
    container_name: blue
    volumes:
      - ./blue:/usr/share/nginx/html:ro
    ports:
      - "8081:80"

  green:
    image: nginx:latest
    container_name: green
    volumes:
      - ./green:/usr/share/nginx/html:ro
    ports:
      - "8082:80"

  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - blue
      - green
